### PR TITLE
Added Worker Pool for Filterers in Retriever

### PR DESCRIPTION
**Pull request by petersng**
Should improve performance as it allows us to run multiple filterers concurrently, whereas before it was done serially. This is in conjunction with the goroutines for filtering each filterers event types, so have to make sure the overall number of goroutines between these two sections doesn't get too high. Lots of I/O waits so shouldn't be a problem, but something to keep in mind.

### CODE REVIEW

**Comment by innainu** [comment]
Ok. This may actually mess up the processing because we currently retrieve events ordered by id (since it was done serially). I'll put in a change after you merge this to order by timestamp.

**Comment by petersng** [comment]
Ok, but even if we run the filterers serially, wouldn't the events be added already be out of order?  If you want to make a change her, just create a branch off this branch and PR into this branch.  That way everything will be in place before we go to master/staging.

**Comment by innainu** [comment]
Yeah, should have clarified: filtering happens serially by event, so we processed all application events first (just bc of the order of the filterers). Anyway, I don't have to make the change to this PR. The processor should handle events out of order so we should test this out on staging to confirm!

**Comment by petersng** [comment]
ok, let's see if it works. the order didn't seem to matter when i tested locally, but 🤞

**Pull request merged**
